#!/bin/bash
version=`date +%s`

jekyll build && jammit --base-url ./

mkdir _site/min
mkdir _site/min/$version

mv min/temp/general.min.css _site/min/$version/general.min.css
mv min/temp/general.min.js _site/min/$version/general.min.js
mv min/temp/general.min.css.gz _site/min/$version/general.min.css.gz
mv min/temp/general.min.js.gz _site/min/$version/general.min.js.gz

rm -rf min/*

for fl in _site/*.html; do
  mv $fl $fl.old
  sed 's/%version%/'$version'/g' $fl.old > $fl
done

rm _site/*.html.old

cp .htaccess _site/.htaccess

rsync -avz --delete --exclude 'logs' --exclude 'usage' --exclude 'mint' _site/ ssh-w00940ce@tobias-otte.de:/www/htdocs/w00940ce/stereobit/

rm -rf _site/*