#!/bin/bash

version=`date +%s`

mkdir public
mkdir public/min
mkdir public/min/temp
mkdir public/min/$version

cp index.html public/index.html
cp .htaccess public/.htaccess
cp favicon.ico public/favicon.ico

jammit

mv public/min/temp/general.min.css public/min/$version/general.min.css
mv public/min/temp/general.min.js public/min/$version/general.min.js
mv public/min/temp/general.min.css.gz public/min/$version/general.min.css.gz
mv public/min/temp/general.min.js.gz public/min/$version/general.min.js.gz

rm -rf public/min/temp

for fl in public/index.html; do
  mv $fl $fl.old
  sed 's/%version%/'$version'/g' $fl.old > $fl
done

rm public/*.html.old