embed_assets: on
package_path: ../min/temp

javascripts:
  general.min:
    - js/dev/lib/jquery.js
    - js/dev/lib/backbone.js
    - js/dev/classes/*.js

stylesheets:
  general.min:
    - css/dev/*.css