embed_assets: on
package_path: ../public/min/temp

javascripts:
  general.min:
    - js/lib/jquery.js
    - js/lib/underscore.js
    - js/lib/backbone.js
    - js/config/templates.js
    - js/config/router.js
    - js/models/*js
    - js/config/init.js

stylesheets:
  general.min:
    - css/*.css